// scripts/build-persona.ts
// Reads SKILL.md + brain/*.md from ../skill/ at build time and emits
// app/_persona.ts containing the full system prompt as a single string
// constant. Lets the Vercel runtime serve responses without filesystem reads.

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';

const ROOT = resolve(__dirname, '..', '..');
const SKILL_DIR = join(ROOT, 'skill');
const BRAIN_DIR = join(SKILL_DIR, 'brain');
const OUT = join(__dirname, '..', 'app', '_persona.ts');

function read(p: string): string {
  return readFileSync(p, 'utf8');
}

function buildPrompt(): string {
  const parts: string[] = [];
  parts.push('=== SKILL.md ===\n' + read(join(SKILL_DIR, 'SKILL.md')));
  const brainFiles = readdirSync(BRAIN_DIR)
    .filter((f) => f.endsWith('.md'))
    .sort();
  for (const f of brainFiles) {
    parts.push(`=== brain/${f} ===\n` + read(join(BRAIN_DIR, f)));
  }
  return parts.join('\n\n');
}

function main(): void {
  const prompt = buildPrompt();
  mkdirSync(dirname(OUT), { recursive: true });
  const content = `// AUTO-GENERATED by scripts/build-persona.ts — do not edit.
// Source: skill/SKILL.md + skill/brain/*.md (${prompt.length.toLocaleString()} chars)

export const BARKLEY_SYSTEM_PROMPT = ${JSON.stringify(prompt)};

export const PROMPT_CHAR_COUNT = ${prompt.length};
`;
  writeFileSync(OUT, content, 'utf8');
  console.log(`Wrote ${OUT} (${prompt.length.toLocaleString()} chars)`);
}

main();
